### ISSUE TITLE
With `shrinkwrap=false` global installs do not work correctly

### ISSUE THREAD

**Issue by jsumners** [pnpm/pnpm#1029]
### Code to reproduce the issue:

1. `echo "shrinkwrap=false" >> ~/.npmrc`
2. `echo "lock=false" >> ~/.npmrc`
3. `pnpm i -g clinic` -- `clinic` is installed correctly
4. `pnpm i -g autocannon` -- `clinic` is removed and `autocannon` is installed

### Expected behavior:

`autocannon` should be added and `clinic` should not be removed.

### Actual behavior:

Only the most recently installed global module is kept.

### Additional information:

 - `node -v` prints: v8.9.4
 - Windows, OS X, or Linux?: macOS and Linux

https://youtu.be/bRmRNWj9QQ8

**Comment by jsumners** [comment]
I'm seeing this bug show up in non-global installs even when the npmrc lines are commented out. For example, if I have a project with dependencies already installed, but I run `NPM_CHECK_INSTALLER=pnpm npm-check -u` to update dependencies then all currently installed dependencies are removed and the newly updated ones are installed.

**Comment by zkochan** [comment]
This bug will happen only when `shrinkwrap=false` and it happens because pnpm compares the wanted shrinkwrap with the current one when removing orphan packages from `node_modules`. The solutions will be to use the current shrinkwrap as the wanted one, when `shrinkwrap` is `false`

**Comment by jsumners** [comment]
Why wouldn't the solution be to ignore the shrinkwrap completely?

**Comment by zkochan** [comment]
the current shrinkwrap is in `node_modules\.shrinkwrap.yaml` and it contains valuable information about the structure of node_modules. Without it, the number of required filesystem operations would grow significantly

**Comment by zkochan** [comment]
fixed in `pnpm@1.32.1`

**Comment by jsumners** [comment]
Thank you.

**Comment by jsumners** [comment]
Has 1.32.1 been published to npmjs.com? I'm still getting 1.32.0 from them.

**Comment by zkochan** [comment]
yes, but it is published with the next dist-tag, so try `... install pnpm@next`

**Comment by jsumners** [comment]
That's working.
