### ISSUE TITLE
Project build error using gulp when dependencies were install using pnpm

### ISSUE THREAD

**Issue by rtorino** [pnpm/pnpm#118]
In my case I am using `gulp-less` plugin to build less files to css. I have no problem if the dependencies were installed using `npm install`, but when using `pnpm install` I got the following error:

`Error: 'tried to require: less'.
None found. Make sure one has been installed!`

**Comment by rstacruz** [comment]
Did you install `less` as well?

**Comment by niftylettuce** [comment]
I got the same error here.

**Comment by niftylettuce** [comment]
Both `less` and `gulp-less` are installed

**Comment by niftylettuce** [comment]
Looks to me like `gulp-less` requires `less` through the `accord` package:

![screen shot 2016-04-22 at 3 31 05 pm](https://cloud.githubusercontent.com/assets/523141/14752776/45964914-089f-11e6-9562-51607aebb0b8.png)

**Comment by iamstarkov** [comment]
@niftylettuce can you try with latest pnpm?

**Comment by zkochan** [comment]
@niftylettuce ping

**Comment by haggholm** [comment]
I just encountered this problem today with the latest version of `pnpm` (0.39.0).

**Comment by HenryTheHamster** [comment]
Also encountered this problem on `0.40.0`

**Comment by HenryTheHamster** [comment]
Just to update our findings on this:
`version == 0.40.0`
Subsequent to a `pnpm i`, if we install `gulp` and `gulp-less` locally using `pnpm`, the `less: None found` error goes away, but we get hit by a different gulp error, namely missing babel transforms (also included by a dep), which suggests, at least for our purposes, that we really do need a flat NPM 3 structure for this to be a viable replacement to NPM.
`npm i` continues to work fine (albeit very slowly)

Keep up the great work guys!

**Comment by zkochan** [comment]
@HenryTheHamster I published the flat tree emulation under the next dist-tag. Try `npm i -g pnpm@next`. Then try to use it with the `--flat-tree` option.

**Comment by HenryTheHamster** [comment]
We're still getting a `Error: 'tried to require: less'. None found. Make sure one has been installed!` when installing using `--flat-tree` and version `0.42.4`. I'd like to test this a bit more thoroughly, but I'm currently on a very shaky network, so will have to wait till tonight.

**Comment by HenryTheHamster** [comment]
Confirmed the above - this is still a bug :(

**Comment by zkochan** [comment]
In that case I assume the problem isn't connected with the flat tree structure. I assume it is related to peerDependencies https://github.com/rstacruz/pnpm/issues/433.

**Comment by zkochan** [comment]
This issue appeared in one of my projects as well. Seems like accord is searching for the dependencies ignoring symlinks. We'll probably have to file an issue there

**Comment by zkochan** [comment]
I looked into accorn and resolve and both seem to work fine.

I see to possible issues here:

1. you might run the task with a gulp that was installed not via pnpm. You have to install the global gulp with pnpm in order to make this work because gulp has to be executed with the `--preserve-symlinks` option
2. if you run it directly. Link `node index.js`, then you'll have to run it with the `--preserve-symlinks` parameter. An important note: the parameter should be at the beginning. So you have to run `node --preserve-symlinks index.js`

**Comment by iamstarkov** [comment]
@rtorino can you try to run your gulp from npm script? or directly from `./node_modules/.bin/gulp`?

**Comment by zkochan** [comment]
Fixed in [pnpm@0.52.0](https://github.com/pnpm/pnpm/releases/tag/v0.52.0). Release under the next dist-tag for now

**Comment by TigersWay** [comment]
Still get the original error as of today! 
```
pnpm -v
1.24.3
```
gulp & gulp-less installed with **npm**: ok
gulp & gulp-less installed with **pnpm** (with the simpliest silly test files)
```
module.js:557
    throw err;
    ^

Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.resolve (internal/module.js:18:19)
    at resolve_engine_path (/home/ben/TigersWay/projects/tryGulp/node_modules/.registry.npmjs.org/accord/0.27.3/node_modules/accord/lib/index.js:65:18)
    at Object.exports.load (/home/ben/TigersWay/projects/tryGulp/node_modules/.registry.npmjs.org/accord/0.27.3/node_modules/accord/lib/index.js:25:19)
    at Object.<anonymous> (/home/ben/TigersWay/projects/tryGulp/node_modules/.registry.npmjs.org/gulp-less/3.4.0/node_modules/gulp-less/index.js:9:29)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```
I can then add less which **should not be needed as already added by gulp-less** and it's working

**Comment by zkochan** [comment]
FYI, accord has been published with a fix, but it was published as a breaking change, so I created a PR to gulp-less: https://github.com/stevelacy/gulp-less/pull/281

once gulp-less will be published with the new accord, this issue will be fixed.

**Comment by zkochan** [comment]
@stevelacy thanks!

This issue is now solved finally :tada:
