### ISSUE TITLE
macOS install error EACCES

### ISSUE THREAD

**Issue by quinton-ashley** [pnpm/pnpm#1203]
```
$ pnpm install -g pnpm
 ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'
```

**Comment by zkochan** [comment]
related #928 (similar issue on Windows)

**Comment by quinton-ashley** [comment]
Why does it need access to this directory?  Can this be fixed without editing permissions?

**Comment by zkochan** [comment]
yes, I think pnpm should write to a folder where it has access already. There should not be any additional steps from users.

**Comment by quinton-ashley** [comment]
I agree

**Comment by zkochan** [comment]
@quinton-ashley I need your help because I don't have a macOS

what does this print? `npm root -g` and this `npm prefix -g`?

also, check the content of the `npmrc` file installed in the root of the globally installed npm. It should contain `prefix=<some path>`

**Comment by fineline** [comment]
Hi @zkochan I have come across this issue too so here are my answers to your question from 25 June, hopefully this can help you progress a fix to this issue.

`npm root -g` prints:
`/usr/local/lib/node_modules`

`npm prefix -g` prints:
`/usr/local`
And that is the same value in the npmrc file too.

**Comment by fineline** [comment]
I started getting the following message whenever running pnpm for installs:

```
   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 2.12.2 → 2.13.1                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v2.13.1   │
   │                  Run pnpm i -g pnpm to update!                   │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

```
However, trying the recommended command resulted in the error in this issue:

```
$ pnpm i -g pnpm
 ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'
```

So I have worked around this by manually creating the folder and taking ownership of it:

```
sudo mkdir '/usr/local/pnpm-global'
sudo chown <myusername> pnpm-global
```

So it's working for now. Suggest that this may be a confusing user experience for those following the notification though.

**Comment by aleclarson** [comment]
I also ran into this.

```sh
$ pnpm --version
2.17.4

$ npm prefix -g
/usr/local
```

I fixed it by doing: `npm config set prefix $HOME`

I don't know what I did for this error to appear, but at least there's a workaround. :)

One more thing: [NVM](https://github.com/creationix/nvm) was also having hiccups when `npm prefix -g` was `/usr/local`. I had to do `nvm install node` to fix that. But these two issues may be related.

**Comment by aleclarson** [comment]
Downgrading the `node` version does nothing.

**Comment by aleclarson** [comment]
Here's what finally fixed it for me: https://github.com/creationix/nvm/issues/1923#issuecomment-429492203

It may also help with this issue, not sure.

**Comment by aleclarson** [comment]
Why does `pnpm install -g` need `npm prefix -g` in the first place?

**Comment by zkochan** [comment]
if NVM creates some env variable that contains the global prefix, we can read that variable and install pnpm to that location

**Comment by aleclarson** [comment]
As a workaround, I can do `pnpm install -g foo --prefix $HOME` so that NVM keeps working.

I think NVM is the problem here, at least in my case. I should be able to set `prefix` to whatever I wish, and NVM should not complain.

**Comment by zkochan** [comment]
You can also set the `pnpm-prefix` config to change the location of global pnpm
`pnpm install -g foo --pnpm-prefix $HOME`

**Comment by aleclarson** [comment]
@zkochan Is that another workaround, or is there some nuance I'm missing?

**Comment by aleclarson** [comment]
I ended up patching NVM myself as a workaround ([see here](https://github.com/creationix/nvm/issues/1923#issuecomment-437590013)).

It's not PNPM's problem, in my opinion.

**Comment by czerwonkabartosz** [comment]
I had a similar problem.

```
Error: EACCES: permission denied, mkdir '/Users/xxx/.pnpm-store/2/registry.npmjs.org/@types/node/10.12.6/_tmp_96278_4fbf8e00003a2ca4d082c374b8c81a20'
```

But I've found a solution for this `sudo rm -rf /Users/xxx/.pnpm-store` 😂  and after this everything works perfectly.

**Comment by sbussard** [comment]
I'm having the same problem:`.pnpm-store` is owned by the root user. 
I think the problem is that `npm` requires sudo to install the `pnpm` cli, so the permissions may be an artifact of that situation

**Comment by rodrigobdz** [comment]
I tried re-installing `pnpm` and then again updating it but the error persists: 
```zsh
$ npm install -g pnpm
$ pnpm install -g pnpm
 ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'
```

**Comment by Flo3719** [comment]
For me the following solved the problem:
`npm config set unsafe-perm true`
and than run `npm install -g pnpm` again.

**Comment by Amirm73** [comment]
@Flo3719 worked for me too, is it necessary to do `npm config set unsafe-perm false` after all?

**Comment by Sujeetkr11** [comment]
@Flo3719 - Thanks! finally this worked for me too
npm config set unsafe-perm true

**Comment by elliottmangham** [comment]
Any solution to this? Making it unusable for me as I cannot install it without sudo.

**Comment by zkochan** [comment]
This should work in the latest pnpm.

Try to install v5.2.9 and then update it to the latest through `pnpm add -g pnpm`

**Comment by danysz** [comment]
I have version 5.5.1 and the problem is still here

**Comment by zkochan** [comment]
what error do you get? no additional info?

**Comment by danysz** [comment]
> what error do you get? no additional info?

` ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'`

**Comment by danysz** [comment]
> > what error do you get? no additional info?
> 
> ` ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'`

please let me know which info you would like to get to help you to solve the issue

**Comment by joeldenning** [comment]
I also see the problem on osx, for global installations

```
pnpm install --global js-correct-lockfile@latest
 ERROR  EACCES: permission denied, open '/usr/local/pnpm-global/4/_tmp_26533_89f97352380e466d8a6135292f20ab16'
```

The problem appears to be that `pnpm` is trying to access a file that doesn't exist:

```sh
$ stat /usr/local/pnpm-global/4/_tmp_26533_89f97352380e466d8a6135292f20ab16

stat: /usr/local/pnpm-global/4/_tmp_26533_89f97352380e466d8a6135292f20ab16: stat: No such file or directory```

I do not know what that tmp folder is for or why pnpm is trying to access it.

**Comment by zkochan** [comment]
I see, where should pnpm try to create the global node_modules directory if it has no permission to write to the user directory?

**Comment by joeldenning** [comment]
I worked around this by running `npm config set prefix $HOME`.

**Comment by joeldenning** [comment]
I think the home directory would be an okay default if pnpm doesn't have permissions for /usr/local.

**Comment by zkochan** [comment]
Try pnpm@6.0.0-20210228

**Comment by zkochan** [comment]
Easiest way to test is

```
curl -L https://unpkg.com/pnpm@6.0.0-20210228/dist/pnpm.js | node - add --global pnpm
```

**Comment by joeldenning** [comment]
I think my current installation of pnpm might be messed up, as i've done some commands with `sudo` and also manually changed permissions of directories to try to get commands working.

Here's what happens when I attempt to install that version of pnpm:

> ~/c/single-spa-workshop.com (main|✚4…) [1] $ curl -L https://unpkg.com/pnpm@6.0.0-20210228/dist/pnpm.js | node - add --global pnpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4409k    0 4409k    0     0  11.6M      0 --:--:-- --:--:-- --:--:-- 11.6M
Packages: +1
> +
> Progress: resolved 1, reused 1, downloaded 0, added 0, done
 ERROR  EPERM: operation not permitted, chmod '/Users/joeldenning/pnpm-global/5/node_modules/pnpm/bin/pnpm.js'

**Comment by zkochan** [comment]
I see, but it tried to write to the user directory, so seems like the fix
will work.

Joel Denning <notifications@github.com> ezt írta (időpont: 2021. febr. 28.,
V 18:09):

**Comment by cupcakearmy** [comment]
> Easiest way to test is
> 
> ```
> curl -L https://unpkg.com/pnpm@6.0.0-20210228/dist/pnpm.js | node - add --global pnpm
> ```

This seems to work for me, the current installer `curl -f https://pnpm.js.org/pnpm.js | node - add --global pnpm` throws the same error 

```
curl -f https://pnpm.js.org/pnpm.js | node - add --global pnpm
 ERROR  EACCES: permission denied, mkdir '/usr/local/pnpm-global'
```

**Comment by meglio** [comment]
Still issue for me, can't install global packages nor upgrade pnpm, the error shown is:

> EACCES: permission denied, mkdir '/usr/local/pnpm-global'

**Comment by zkochan** [comment]
This is fixed in pnpm v6

**Comment by LaamGinghong** [comment]
@zkochan The problem remains.
![image](https://user-images.githubusercontent.com/33472924/143805919-04bedcb0-4c9a-45fb-a35c-686da52b6e9c.png)
![image](https://user-images.githubusercontent.com/33472924/143805965-e7ed30a5-e8df-483a-bce3-e0108b833ce0.png)

**Comment by zkochan** [comment]
@LaamGinghong do you remember how have you installed pnpm the first time?

**Comment by LaamGinghong** [comment]
> 

maybe use curl.  I'm not sure.

**Comment by wzrove** [comment]
```
EPERM: operation not permitted, chmod '$home/.nvm/versions/node/v17.5.0/pnpm-global/5/node_modules/.pnpm/pnpm@6.32.2/node_modules/pnpm/bin/pnpm.cjs'
```
when update pnpm get Error

**Comment by anurag-roy** [comment]
Just setting up a new mac, and this time I decided to install pnpm through homebrew.

Now when I try to install any global package

```sh
pnpm add -g ts-node
 ERROR  EACCES: permission denied, mkdir '/Users/anurag/Library/pnpm'
For help, run: pnpm help add
```
