### ISSUE TITLE
pnpm run does not set correct $npm_execpath

### ISSUE THREAD

**Issue by kub1x** [pnpm/pnpm#1742]
`pnpm` passes `run` commands to `npm`. This also means `$npm_execpath` is set to `npm` binary. I can not call commands such as `update` or `outdated` from within `package.json` scripts using `$npm_execpath` as they would be called with `npm` and fail. 

If possible `$npm_execpath` should be correctly set to `pnpm`. 

### Code to reproduce the issue:
In `package.json`: 
```json
"scripts": {
    "lint": "eslint",
    "check": "$npm_execpath outdated --depth 0",
    "prepare": "$npm_execpath run lint && $npm_execpath run check"
}
```

When I do `pnpm run check` the `outdated` command is run by `npm` instead of `pnpm`. I need the `$npm_execpath` approach as developers might use whatever pm they like, CI uses `npm` and I would like to use `pnpm`. 

* If I hardcoded `pnpm` inside `package.json` I would have to add it to dependencies for CI which I find ugly. 
* If I hardcoded `npm` inside `package.json`, npm would fail on checking outdated packages as it doesn't accept linked packages. 

### Expected behavior:
```
$ pnpm run check

> $npm_execpath outdated --depth 0

$
```
Exits with success.

### Actual behavior:

```
$ pnpm run check

> $npm_execpath outdated --depth 0

Package                       Current    Wanted    Latest  Location
eslint                         linked    5.15.3    5.15.3  rodnecislo
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rodnecislo@1.2.0 check: `$npm_execpath outdated --depth 0`
npm ERR! Exit status 1
```

Exits with 1 as `npm` is called behind the scene. 

### Additional information:

 - `node -v` prints: v11.12.0
 - linux

**Comment by zkochan** [comment]
:ship: 3.3.0-0
via #1805

**Comment by zkochan** [comment]
It is not related but in order to support `json5,yaml`, pnpm had to reimplement `pnpm run` and other commands. In the reimplemented command this is fixed.

You don't need to use json5 or yam. It will work with `package.json`

**Comment by rxliuli** [comment]
> It is not related but in order to support `json5,yaml`, pnpm had to reimplement `pnpm run` and other commands. In the reimplemented command this is fixed.
> 
> You don't need to use json5 or yam. It will work with `package.json`

Sorry, can you explain it in more detail? I discovered that currently the pnpm exec and pnpm create commands still don't set $npm_execpath correctly. I wanted to file a PR to modify it, but couldn't find the right entry.

ref: https://github.com/pnpm/pnpm/issues/7037
