### ISSUE TITLE
Empty tmp folders created in root directory

### ISSUE THREAD

**Issue by dougwaldron** [pnpm/pnpm#2749]
Running `pnpm install` leaves an empty "_tmp" folder in the root directory. These accumulate over time:

![image](https://user-images.githubusercontent.com/737326/89345898-357b9d00-d676-11ea-8fa5-b84133dbf09b.png)

pnpm version: 5.4.11

**Comment by dougwaldron** [comment]
Running on Windows 10 version 1803

**Comment by zkochan** [comment]
should big fixed in v5.0.0-1

**Comment by Daniel-Khodabakhsh** [comment]
I'm on 5.5.1 and it's still happening. Windows 10 1607.

**Comment by TigersWay** [comment]
Finally understood all these folders were from pnpm.....
So running v5.5.13 and still happening, at least on every "up" command.

_In case it matters, Windows is 1009, node is on C: under nvm, projects and pnpm store on D:_

**Comment by creepinson** [comment]
Same problem, any updates?

**Comment by zkochan** [comment]
no, I did not work on a fix yet. The fix will probably be in the store-path package

**Comment by kuznetsov-online** [comment]
I have the same problem on Mac

**Comment by zkochan** [comment]
:ship: 5.13.1
