### ISSUE TITLE
pnpm creates invalid symlinks

### ISSUE THREAD

**Issue by mtford90** [pnpm/pnpm#2916]
Creating this issue as requested by @zkochan on discord. 

![](https://cdn.discordapp.com/attachments/731599538665553975/764034783457837056/Screenshot_2020-10-09_at_08.58.17.png)

### pnpm version:

```
$ pnpm --version
5.8.0
```

### Code to reproduce the issue:

https://github.com/mtford90/timberwolf/tree/try-pnpm

```bash
git clone https://github.com/mtford90/timberwolf.git
cd timberwolf
git checkout try-pnpm
pnpm install
ls node_modules # observe broken symlinks.
```

### Expected behavior:

There should be no invalid symlinks

### Actual behavior:

Symlinks are pointing to nowhere.

### Additional information:

 - `node -v` prints: v14.7.0
 - Windows, OS X, or Linux?: macOS Catalina 10.15.6

**Comment by zkochan** [comment]
I see, so these are optional dependencies that are skipped. Hoisting still creates the symlinks to them even though they are not installed.

We should fix this probably but I don't think it is a high priority as those packages should not be installed and everything should be functional even with a few broken symlinks inside node_modules.

**Comment by mtford90** [comment]
@zkochan ah, this must be a naughty package then...

if you try `pnpm run rebuild:electron` it will fail due to missing `async-each` which indicates these packages should not in fact be optional.

**Comment by mitoihs** [comment]
We have exactly the same issue with invalid symlinks affecting us in multiple ways.

See for example that bug (which is a bug in azure task I think so I've submitted it there, but still won't occur if pnpm won't create invalid symlink): https://github.com/microsoft/azure-pipelines-tasks/issues/13688

Another similar issue we have with SonarQube which also scans everything and crashes on invalid symlink.

Of course those tools may just not fail when spotting invalid symlink, but they do and here's a simple and centralized solution - don't create them.

**Comment by zkochan** [comment]
:ship: 5.13.7

**Comment by CodeAunt** [comment]
I removed and repulled the directory, the error was fixed.
I'm not sure what's the reason. Removing all cached modules and lock files didn't help. 
Could also try this.
