### ISSUE TITLE
[7.4.0-0] Patch not applied

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/pnpm#4914]
### pnpm version: 7.4.0-0

I run `pnpm patch ts-results@3.3.0` and commit the changes.

![image](https://user-images.githubusercontent.com/5390719/175205668-51c8cb69-eb8b-4e3b-9ce4-8062554c909f.png)

![image](https://user-images.githubusercontent.com/5390719/175205702-9f0f1dfb-db5d-4fbb-a53e-e362560f36b9.png)

But the files in node_modules are not patched.

![image](https://user-images.githubusercontent.com/5390719/175205763-2963eb1c-162f-4303-ba4c-a550f57f86d4.png)

### Additional information:

 - `node -v` prints: 18.3.0
 - Windows, macOS, or Linux?: Windows

### Reproduction

1. Repo: https://github.com/DimensionDev/Maskbook/
2. Checkout `develop` branch and run `pnpm install` (we use a forked version of patch-package that support pnpm before)
3. Install at `develop` branch might corrupt the pnpm global store (because it modifies node_modules directly). I don't know if this problem is related to the corrupted global store.
4. checkout `pnpm-patch` branch and run `pnpm install`
5. ts-results package is not patched.

**Comment by zkochan** [comment]
The issue is that you disallowed builds

https://github.com/DimensionDev/Maskbook/blob/c2c18248695f9ee18cda833a86ca012d1bdadba5/package.json#L96

I implemented patching as a build step.

**Comment by zkochan** [comment]
Maybe you need remove your node_modules after removing onlyBuiltDependencies

**Comment by Jack-Works** [comment]
https://user-images.githubusercontent.com/5390719/175565963-81557c21-57a1-4cca-b3f3-da3e4cb505b8.mp4

I create a new VM and it doesn't have any cache in it but it still not working.

**Comment by zkochan** [comment]
Try with `3.4.0-1`. The lockfile will have a different format.
