### ISSUE TITLE
`pnpm i` get stuck forever on `postinstall` script

### ISSUE THREAD

**Issue by chungweileong94** [pnpm/pnpm#5909]
### Code to reproduce the issue: 
`pnpm install`

### Expected behavior: 
All packages successfully installed

### Actual behavior: 
Get stuck in one of the `postinstall` scripts from a package
![image](https://user-images.githubusercontent.com/15154097/211574769-64d2d0c2-36fc-4a5b-84ef-cd607c271ed9.png)

### Additional information:

 - `node -v` prints: v16.19.0
 - Windows, macOS, or Linux?: macOS

**Comment by chungweileong94** [comment]
Not sure if this is related to https://github.com/pnpm/pnpm/issues/5823.
If you remove `node_modules`, then run `pnpm i`, it will run perfectly fine. But it will get stuck in subsequence `pnpm i`

**Comment by dragonfire1119** [comment]
I fixed it with a strange solution.

1. Save the pnpm-lock.yaml file or keep it versioned.
2. Remove the pnpm-lock.yaml and node_modules files. ``rm -rf node_modules && pnpm install``
3. Run ``pnpm install`` generates a new pnpm-lock.yaml file.
4. Delete or restore your old pnpm-lock.yaml file.
5. Rerun ``rm -rf node_modules && pnpm install``, and it should run the postinstall.

This worked for me, and I hope it can help others!

**Comment by chuankaiwei** [comment]
same issue.  hang up during `postinstall`.

**Comment by shirotech** [comment]
Agreed, probably same as #5823

**Comment by zkochan** [comment]
Please create a repo that reproduces the issue.

**Comment by nowlena** [comment]
same issue here

**Comment by chungweileong94** [comment]
> Please create a repo that reproduces the issue.

Here's a small repo that reproduces the problem
https://github.com/chungweileong94/pnpm-hang-up-bug

Two key things in this repo:
- `node-linker=hoisted`
- A package that contains `postinstall`

**Comment by sleaper** [comment]
Same issue.

**Comment by zkochan** [comment]
I don't have issues running install on the example repo: https://github.com/chungweileong94/pnpm-hang-up-bug

**Comment by edmbn** [comment]
> I don't have issues running install on the example repo: https://github.com/chungweileong94/pnpm-hang-up-bug

I also experience this now with prisma. Keep in mind that it's not happening on first install. This starts happening with the second install.

**Comment by zkochan** [comment]
I assume it stopped working in v7.19.0 due to these changes: https://github.com/pnpm/pnpm/pull/5814

**Comment by zkochan** [comment]
This line could stuck: https://github.com/pnpm/pnpm/blob/4655dd41e1b59ebe60fba042a66c499b468e18fc/exec/build-modules/src/index.ts#L99

But I cannot think of a scenario when it would happen. I the finally block it is resolved: https://github.com/pnpm/pnpm/blob/4655dd41e1b59ebe60fba042a66c499b468e18fc/exec/build-modules/src/index.ts#L176

**Comment by zkochan** [comment]
Looks like this happens a lot but I cannot reproduce it. Please try to debug it yourself and see where and why the issue happens. Also might be useful to find out which exact version of pnpm has introduced the issues (or even which commit).

**Comment by chungweileong94** [comment]
Not sure if this info is useful, but the memory keeps building up over time unless I kill the process manually.
![image](https://user-images.githubusercontent.com/15154097/212915533-96b62639-c203-4362-aabe-1f0669c9ec3e.png)

**Comment by chungweileong94** [comment]
> Looks like this happens a lot but I cannot reproduce it. Please try to debug it yourself and see where and why the issue happens. Also might be useful to find out which exact version of pnpm has introduced the issues (or even which commit).

I specifically remember I was facing issue #5823, then it was fixed by #5902, however, it started to have this issue.

**Comment by chungweileong94** [comment]
> Try to run with `pnpm install --reporter ndjson` and attach the output.

```
{"time":1673966063325,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:scope","selected":1}
{"time":1673966063336,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:package-manifest","initial":{"name":"pnpm-hang-up-bug","version":"1.0.0","description":"","main":"index.js","scripts":{"test":"echo \"Error: no test specified\" && exit 1"},"keywords":[],"author":"","license":"ISC","dependencies":{"prisma":"^4.8.1"}},"prefix":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug"}
{"time":1673966063338,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:context","currentLockfileExists":true,"storeDir":"/Volumes/MacExtDrive/.pnpm-store/v3","virtualStoreDir":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug/node_modules/.pnpm"}
{"time":1673966063338,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"info","name":"pnpm","message":"Lockfile is up to date, resolution step is skipped","prefix":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug"}
{"time":1673966063339,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:stage","prefix":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug","stage":"importing_started"}
{"time":1673966063343,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:stats","added":2,"prefix":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug"}
{"time":1673966063343,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:stats","prefix":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug","removed":0}
{"time":1673966063347,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:stage","prefix":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug","stage":"importing_done"}
{"time":1673966063347,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:package-manifest","prefix":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug","updated":{"name":"pnpm-hang-up-bug","version":"1.0.0","description":"","main":"index.js","scripts":{"test":"echo \"Error: no test specified\" && exit 1"},"keywords":[],"author":"","license":"ISC","dependencies":{"prisma":"^4.8.1"}}}
{"time":1673966063351,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:lifecycle","depPath":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug/node_modules/@prisma/engines","optional":false,"script":"node scripts/postinstall.js","stage":"postinstall","wd":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug/node_modules/@prisma/engines"}
{"time":1673966063655,"hostname":"Chung-Weis-Mac-mini.local","pid":53819,"level":"debug","name":"pnpm:lifecycle","depPath":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug/node_modules/@prisma/engines","exitCode":0,"optional":false,"stage":"postinstall","wd":"/Volumes/MacExtDrive/Projects/pnpm-hang-up-bug/node_modules/@prisma/engines"}

```

**Comment by rodolphoasb** [comment]
Same error here:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/8127858/212958127-9c78bda7-e4f2-4d0d-a227-3870a84bc744.png">

pnpm v7.25.0 and v7.23.0

**Comment by kickbk** [comment]
+1

**Comment by zkochan** [comment]
> It seems to happen on secondary or external volumes and not on main? Can you confirm? I'm also facing the same issue. Also mac as well.

I have tried to reproduce it by running install on a flash drive. It didn't stuck for me.

**Comment by zkochan** [comment]
@pnpm/collaborators if anyone can reproduce this, please help me find the issue.

**Comment by shirotech** [comment]
> > It seems to happen on secondary or external volumes and not on main? Can you confirm? I'm also facing the same issue. Also mac as well.
> 
> I have tried to reproduce it by running install on a flash drive. It didn't stuck for me. (on macOS as well)

Maybe our setup is a bit different, on Mac there is a thing called Volumes, not a physical partition, it's more logical. It will give the same space as the original. Perhaps that could be it.

<img width="732" alt="Screenshot 2023-01-18 at 9 39 56 am" src="https://user-images.githubusercontent.com/1149825/213028011-6cdefd4f-8e61-4e78-a591-e59e9c1236c5.png">

The reason I have done it this way is to enable case sensitive for certain directories, because Mac decides to have file system case insensitive by default, which is bad for git.

**Comment by chungweileong94** [comment]
So I tested it on my work machine with only one drive (main drive), and everything seems to work fine.
FYI, I was facing the issue when the codebase is in an external drive.

**Comment by zkochan** [comment]
Then maybe it gets stuck at this point:

https://github.com/pnpm/pnpm/blob/94ef3299edbd0dca2ba1b0ed2d5525f15fb0995b/exec/build-modules/src/index.ts#L173

**Comment by zkochan** [comment]
It looks like it gets stuck here: https://github.com/pnpm/pnpm/blob/main/fs/hard-link-dir/src/index.ts

I don't know why, someone needs to debug it. See [contributing](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md) how to setup pnpm locally. You can use console logs, run `pnpm -w compile` to update the code and run `pd i --reporter=append-only`.

If the issue is reproducible constantly and you don't know how to debug it, then ping me on discord.

**Comment by erickreutz** [comment]
Also, running into this. It finally blew up. 

```
<--- Last few GCs --->

[74518:0x128008000]   928428 ms: Mark-sweep 4045.0 (4140.2) -> 4034.7 (4142.7) MB, 1708.3 / 0.0 ms  (average mu = 0.415, current mu = 0.261) task scavenge might not succeed
[74518:0x128008000]   931816 ms: Mark-sweep 4047.5 (4142.7) -> 4037.1 (4145.2) MB, 2803.8 / 0.0 ms  (average mu = 0.285, current mu = 0.172) task scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10259c46c node::Abort() [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
 2: 0x10259c5f4 node::errors::TryCatchScope::~TryCatchScope() [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
 3: 0x1026ea7b4 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
 4: 0x1026ea748 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
 5: 0x10286dc08 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
 6: 0x10286c728 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
 7: 0x1028e3bb8 v8::internal::ScavengeJob::Task::RunInternal() [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
 8: 0x1025fa12c node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
 9: 0x1025f8dc4 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
10: 0x102e09b10 uv__async_io [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
11: 0x102e1b824 uv__io_poll [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
12: 0x102e09fa0 uv_run [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
13: 0x1024ece00 node::SpinEventLoop(node::Environment*) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
14: 0x1025d5638 node::NodeMainInstance::Run(int*, node::Environment*) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
15: 0x1025d5304 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
16: 0x10256e2ec node::Start(int, char**) [/Users/eric/.asdf/installs/nodejs/16.13.1/bin/node]
17: 0x1a82dfe50 start [/usr/lib/dyld]
zsh: abort      pnpm i react-native-tab-view --reporter ndjson --filter @my/ui
pnpm i react-native-tab-view --reporter ndjson --filter @my/ui  148.14s user 819.78s system 103% cpu 15:32.09 total
```

**Comment by erickreutz** [comment]
Furthermore, downgrading to `7.18.2` seems to fix the issue. Using `7.19.0` results in `WARN An error occurred while uploading` for various packages (the same as https://github.com/pnpm/pnpm/issues/5823) and using `7.24.0` gets rid of the warning but then results in the hang that this issue is related to.

**Comment by zkochan** [comment]
We have debugged it a bit with @kickbk 

These are some of the findings so far:

1. it looks like the issue is gone if `package-import-method=copy` is set in `.npmrc` (or you run `pnpm install --package-import-method=copy`
2. we tested it on an expo mono repo. It got stuck at this function call:

https://github.com/pnpm/pnpm/blob/98d6603f317a9ab28a2181aabbf63dd0f98d3804/pkg-manager/headless/src/linkHoistedModules.ts#L136-L140

It got stuck when linking bins to `node_modules/react-native/node_modules/.bin`

**Comment by paulclark** [comment]
Another macOS user here experiencing this on `7.25.0`. Downgrading to `7.18.2` resolved per @erickreutz's suggestion.

I'm in a monorepo similar to [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo/), with the same `.npmrc`:
```
node-linker=hoisted

public-hoist-pattern[]=*prisma*

strict-peer-dependencies=false
```

Happy to assist with any other logging/debugging if needed.

**Comment by zkochan** [comment]
It looks like it works if `prefer-symlinked-executables` is set to `false`, or this line is commented out:

https://github.com/pnpm/pnpm/blob/5bede17edb5359daf6078bf69d488069b1b2ceba/pkg-manager/link-bins/src/index.ts#L214

**Comment by nowlena** [comment]
> It looks like it works if `prefer-symlinked-executables` is set to `false`, or this line is commented out:
> 
> https://github.com/pnpm/pnpm/blob/5bede17edb5359daf6078bf69d488069b1b2ceba/pkg-manager/link-bins/src/index.ts#L214

can confirm, changing this setting in my npmrc seems to have resolved the problem

**Comment by zkochan** [comment]
@paulclark if it reproduces for you on each run, you can call me on discord and we can debug it together. 

Or you can debug it yourself and post your findings. I have to assumptions currently. It either gets stuck here:

https://github.com/pnpm/pnpm/blob/5bede17edb5359daf6078bf69d488069b1b2ceba/pkg-manager/link-bins/src/index.ts#L214

or here:

https://github.com/pnpm/pnpm/blob/5bede17edb5359daf6078bf69d488069b1b2ceba/exec/build-modules/src/index.ts#L173

**Comment by zkochan** [comment]
@nowlena does it work if you set `prefer-symlinked-executables` back to `true` but comment out this:

https://github.com/pnpm/pnpm/blob/5bede17edb5359daf6078bf69d488069b1b2ceba/pkg-manager/link-bins/src/index.ts#L214

**Comment by nowlena** [comment]
> 

Sorry, I'm not sure where the pnpm source files are to modify them.

When I `which pnpm` I get `/home/name/.nvm/versions/node/v18.12.1/bin/pnpm` though didn't find anything useful around there.

**Comment by zkochan** [comment]
@nowlena see [contributing](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md) how to setup pnpm locally. You can use console logs, run `pnpm -w compile` to update the code and run `pd i --reporter=append-only`.

**Comment by zkochan** [comment]
I have uploaded a video about how to debug pnpm with console.log statements: https://youtu.be/Q_DK1gzIV0I

Use this if you can reproduce the issue locally and want to help localising the issue. I have listed above potential places where this could get stuck.

**Comment by mgcrea** [comment]
Encountering this as well, @zkochan do you still need help debugging this or have you found the proper fix? Looks like https://github.com/pnpm/pnpm/commit/1072ec12869fcad320459754b5fbbac09d7787a0 might be related?

Was trying to debug locally but `pnpm run compile` fails (both on tag `v7.25.1` and latest) on the following command `tsc --build && pnpm run lint --fix` because of missing declarations:

> error TS2307: Cannot find module 'typanion' or its corresponding type declarations.

**Comment by zkochan** [comment]
>@zkochan do you still need help debugging this or have you found the proper fix? Looks like https://github.com/pnpm/pnpm/commit/1072ec12869fcad320459754b5fbbac09d7787a0 might be related?

That fix is unrelated to this issue.

>FYI, I was trying to debug locally but pnpm run compile fails (both on tag v7.25.1 and latest) on the following command tsc --build && pnpm run lint --fix because of missing declarations:
>
>error TS2307: Cannot find module 'typanion' or its corresponding type declarations.
>Fixed with packages/mount-modules; pnpm add typanion. Not sure if there is something wrong with my setup.

I don't get this issue but it should be fixed if it happens

>In my case, it hangs there (the symlinkDir call) when linking esbuild (node_modules/esbuild/bin/esbuild):
>
>https://github.com/pnpm/pnpm/blob/v7.25.1/pkg-manager/link-bins/src/index.ts#L213
>
>Can confirm that it does hog 100% cpu and leaks memory until OOM so looks like an issue with the symlink-dir package.

I think @nowlena got the same result

**Comment by zkochan** [comment]
@mgcrea could you try with this branch: [fix/5909](https://github.com/pnpm/pnpm/tree/fix/5909)? After the switch run `pnpm install`.

I did these changes to symlink-dir: https://github.com/pnpm/symlink-dir/pull/39/files

**Comment by Murtatrxx** [comment]
Hi, strange but a Windows user here, though, I'm not sure this is the same issues that I'm facing. Here's mine:

First steps are the same, but looks like mine doesn't say "done" before it gets stuck on postinstall script. The solutions above does not work.
pnpm i: (.npmrc package import to copy)
![image](https://user-images.githubusercontent.com/77380166/214386758-3982ca84-0086-470c-966a-8ea8baa7cac7.png)
Note: Fails as skipped because I did `CTRL C`

And the `pnpm install --reporter ndjson` output where I believe it stucks.
```txt
{"time":1674587371968,"hostname":"MurathanDK","pid":76460,"level":"debug","name":"pnpm:lifecycle","depPath":"/msgpackr-extract/2.2.0","optional":true,"script":"node-gyp-build-optional-packages","stage":"install","wd":"C:\\Users\\murat\\OneDrive\\Belgeler\\VisualBot\\node_modules\\.pnpm\\msgpackr-extract@2.2.0\\node_modules\\msgpackr-extract"}
{"time":1674587372040,"hostname":"MurathanDK","pid":76460,"level":"debug","name":"pnpm:lifecycle","depPath":"/msgpackr-extract/2.2.0","line":"Microsoft Windows [Version 10.0.25267.1000]","stage":"install","stdio":"stdout","wd":"C:\\Users\\murat\\OneDrive\\Belgeler\\VisualBot\\node_modules\\.pnpm\\msgpackr-extract@2.2.0\\node_modules\\msgpackr-extract"}
{"time":1674587372045,"hostname":"MurathanDK","pid":76460,"level":"debug","name":"pnpm:lifecycle","depPath":"/msgpackr-extract/2.2.0","line":"(c) Microsoft Corporation. All rights reserved.","stage":"install","stdio":"stdout","wd":"C:\\Users\\murat\\OneDrive\\Belgeler\\VisualBot\\node_modules\\.pnpm\\msgpackr-extract@2.2.0\\node_modules\\msgpackr-extract"}
```

**Comment by Murtatrxx** [comment]
But as addition to that, I'm encountering this issues more than 3 weeks, when I started using pnpm

**Comment by florent-uzio** [comment]
+1 I have this issue as well. With `swiper` it is stuck forever.

```
node_modules/swiper: Running postinstall script, done in 102ms
Progress: resolved 0, reused 75, downloaded 0, added 71, done
```

**Comment by bchilcott** [comment]
Also getting this on Windows, with this output for the sample repo provided at the top of this issue:
```
{"time":1674680908070,"hostname":"PC","pid":9136,"level":"debug","name":"pnpm:lifecycle","depPath":"C:\\Repos\\pnpm-hang-up-bug\\node_modules\\@prisma\\engines","optional":false,"script":"node scripts/postinstall.js","stage":"postinstall","wd":"C:\\Repos\\pnpm-hang-up-bug\\node_modules\\@prisma\\engines"}
{"time":1674680908080,"hostname":"PC","pid":9136,"level":"debug","name":"pnpm:lifecycle","depPath":"C:\\Repos\\pnpm-hang-up-bug\\node_modules\\@prisma\\engines","line":"Microsoft Windows [Version 10.0.22621.1105]","stage":"postinstall","stdio":"stdout","wd":"C:\\Repos\\pnpm-hang-up-bug\\node_modules\\@prisma\\engines"}
{"time":1674680908080,"hostname":"PC","pid":9136,"level":"debug","name":"pnpm:lifecycle","depPath":"C:\\Repos\\pnpm-hang-up-bug\\node_modules\\@prisma\\engines","line":"(c) Microsoft Corporation. All rights reserved.","stage":"postinstall","stdio":"stdout","wd":"C:\\Repos\\pnpm-hang-up-bug\\node_modules\\@prisma\\engines"}
```
Interestingly, running any script (pnpm run) results in both powershell both cmd restarting themselves. Below for a NestJS app but the same happens for any script:
```
PS C:\Repos\pnpm-test> pnpm start

> pnpm-test@0.0.1 start C:\Repos\pnpm-test
> nest start

Microsoft Windows [Version 10.0.22621.1105]
(c) Microsoft Corporation. All rights reserved.
```
Having tried this on a Windows sandbox with fresh installations of Node LTS and PNPM, this issue doesn't happen. Nor does it happen when running through WSL2 ubuntu. So I suppose it must be a conflict with something else. I'm not sure if this issue on windows is the same as others OP/others are facing on MacOS.

**Comment by Murtatrxx** [comment]
@bchilcott yeah I also got that

**Comment by Murtatrxx** [comment]
@bchilcott It says "done" when installing postinstall or just nothing, unlike others

**Comment by Murtatrxx** [comment]
But what is stranger though I was taking this issues in pnpm 1.17, also created an issues (#5706) but no one responded

**Comment by bchilcott** [comment]
> @bchilcott does it say "done" when installing postinstall or just nothing, unlike others

You're right, mine doesn't say done. I guess mine must be a separate issue related to the one you opened, rather than this one.

**Comment by Murtatrxx** [comment]
Then move onto mine

**Comment by zkochan** [comment]
This memory issue: https://github.com/pnpm/pnpm/issues/5909#issuecomment-1387394916

is probably fixed in v7.26.1

**Comment by jgoux** [comment]
> This memory issue: [#5909 (comment)](https://github.com/pnpm/pnpm/issues/5909#issuecomment-1387394916)
> 
> is probably fixed in v7.26.1

Hello, I just tested with `v7.26.1` and the issue is still there:

```bash
➜  snaplet-labs git:(main) ✗ pnpm i
Scope: all 11 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +860
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
node_modules/@prisma/engines: Running postinstall script, done in 147ms
node_modules/prisma/node_modules/@prisma/engines: Running postinstall script, done in 147ms
node_modules/turbo: Running postinstall script, done in 140ms

<--- Last few GCs --->

[3192:0x160040000]  1088169 ms: Mark-sweep 4049.7 (4140.7) -> 4039.0 (4143.2) MB, 1907.2 / 0.0 ms  (average mu = 0.578, current mu = 0.253) task; scavenge might not succeed
[3192:0x160040000]  1091659 ms: Mark-sweep 4052.1 (4143.2) -> 4041.4 (4145.5) MB, 2843.5 / 0.0 ms  (average mu = 0.408, current mu = 0.185) task; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x102ca0794 node::Abort() [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
 2: 0x102ca0984 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
 3: 0x102df3790 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
 4: 0x102f9e704 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
 5: 0x102f9d1e8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
 6: 0x10301e3bc v8::internal::ScavengeJob::Task::RunInternal() [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
 7: 0x102cfdc60 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
 8: 0x102cfc8cc node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
 9: 0x1035bcbc8 uv__async_io [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
10: 0x1035cf36c uv__io_poll [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
11: 0x1035bd098 uv_run [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
12: 0x102bf1704 node::SpinEventLoop(node::Environment*) [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
13: 0x102cdcd14 node::NodeMainInstance::Run() [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
14: 0x102c6e614 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
15: 0x102c6e898 node::Start(int, char**) [/Users/jgoux/Library/pnpm/nodejs/18.13.0/bin/node]
16: 0x18fc1fe50 start [/usr/lib/dyld]
[1]    3192 abort      pnpm i
```

**Comment by Murtatrxx** [comment]
😂

**Comment by mgcrea** [comment]
@zs

> @mgcrea could you try with this branch: [fix/5909](https://github.com/pnpm/pnpm/tree/fix/5909?rgh-link-date=2023-01-24T01%3A21%3A46Z)? After the switch run `pnpm install`.
> 
> I did these changes to symlink-dir: [pnpm/symlink-dir#39 (files)](https://github.com/pnpm/symlink-dir/pull/39/files)

Can confirm that this branches fixes it while I still got the error using `v7.26.1` 🎉

**Comment by zkochan** [comment]
@mgcrea thanks, I have released that fix in v7.26.3

**Comment by ngnathan** [comment]
Had the same thing with the `create-t3-turbo` stack.  Fix works in 7.26.3.  Thanks!

For me, it didn't work in 7.26.2.  (And had to downgrade to 7.18.2 as well)

**Comment by zkochan** [comment]
Great, but I am not sure it fixes the initial issue. @chungweileong94 do you still have the issue in v7.26.3?

**Comment by kickbk** [comment]
I tested v7.26.3 and it's working 🎉

**Comment by chungweileong94** [comment]
> Great, but I am not sure it fixes the initial issue. @chungweileong94 do you still have the issue in v7.26.3?

Yeah, the latest version 7.26.3 seems to fix the issue on my side as well. Appreciate the fix and the other people involved👍

**Comment by edgarsilva** [comment]
@zkochan This issue seems to be back in v7.27.0, reverting back to v7.26.3 fixes it.

```bash
- pnpm 7.27.0
+ pnpm 7.26.3 (7.27.0 is available)
```

Here is the output I'm seeing when it fails trying to install a dependency, this is using turborepo and `node-llinker=hoisted` ->

```bash
Relinking /home/edgar/workspace/restoration-md/monorepo/node_modules/log-symbols/node_modules/chalk from the store
../../node_modules/es5-ext: Running postinstall script, done in 49ms
../../node_modules/sharp: Running install script, done in 187ms
../../node_modules/supabase: Running postinstall script, done in 2s
../../node_modules/turbo: Running postinstall script, done in 41ms
../..                                    | Progress: resolved 574, reused 583, downloaded 0, added 36, done

<--- Last few GCs --->

[43850:0x4b9e900]    88618 ms: Mark-sweep 4046.9 (4138.5) -> 4036.4 (4141.0) MB, 2267.4 / 0.0 ms  (average mu = 0.094, current mu = 0.022) task scavenge might not succeed
[43850:0x4b9e900]    90941 ms: Mark-sweep 4049.2 (4141.0) -> 4038.8 (4143.5) MB, 2279.7 / 0.0 ms  (average mu = 0.058, current mu = 0.018) task scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [node]
 3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeaf465  [node]
 6: 0xeaff46  [node]
 7: 0xebe46e  [node]
 8: 0xebeeb0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf222f4 v8::internal::ScavengeJob::Task::RunInternal() [node]
10: 0xdb59db non-virtual thunk to v8::internal::CancelableTask::Run() [node]
11: 0xb77524 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [node]
12: 0xb79389 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
13: 0x15633c6  [node]
14: 0x1575af4  [node]
15: 0x1563d18 uv_run [node]
16: 0xa43dd5 node::SpinEventLoop(node::Environment*) [node]
17: 0xb4bab6 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [node]
18: 0xacd3f2 node::Start(int, char**) [node]
19: 0x7f2c40623510  [/lib/x86_64-linux-gnu/libc.so.6]
20: 0x7f2c406235c9 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
21: 0xa4076c  [node]
fish: Job 1, 'pnpm add @clerk/clerk-react' terminated by signal SIGABRT (Abort)
```

**Comment by zkochan** [comment]
I am not sure why. I did not touch any of the related code.

**Comment by edgarsilva** [comment]
Lol that's weird... I can confirm this happens on Linux and my coworker Mac, same for him reverting to v7.26.3 fixed it.

**Comment by chungweileong94** [comment]
It's probably something else, it doesn't seem to happen in [my sample repo](https://github.com/chungweileong94/pnpm-hang-up-bug), tested with v7.27.0

**Comment by edgarsilva** [comment]
Only happens in that turborepo, removing all `node_modules` directories and the lock file and running `pnpm i` works fine, it's just adding new modules or running package scripts with `pnpm run` inside any of the apps or packages in the turborepo that breaks it.

My guess is it has to do with the .npmrc config, which has`node-linker=hoisted` and `strict-peer-dependencies=false`.

I don't have more time to debug it till  the weekend, I'll see if there's any more info on the root cause I can find and share it here.

**Comment by Chitranjan23** [comment]
Facing the same issue 8.1.1

**Comment by tylergannon** [comment]
In case it helps: I was getting this issue consistently on newly created sveltekit apps, using
`pnpm create svelte@latest my-app` and then choosing Skeleton project with Typescript and all additional options.

I could reliably see `pnpm i` freeze after 15 packages being installed, but if I delete and re-create and install using `npm i` it would work fine.

I'm on pnpm 8.5.0.

Upgrading from nodejs LTS 18.12.1 to nodejs current (20.1.0) resolved the issue.

**Comment by withinoneyear** [comment]
no sure if my one is the same. I'm using pnpm in a monorepo with `shamefully-hoist=true`, when running `pnpm i` it starts to resolve and will hang when it resolves 158 packages, and it will stay there for around 30 seconds and then continue. Not sure why is happening when it is stuck

The total time to even add a small package is 42s while for yarn it only takes 13s with the same repo.

**Comment by tamvo22** [comment]
I encountered the same frozen issue when upgrading from pnpm@8.15.7 to pnpm@9.0.0 and the latest (9.0.6). 

After the upgrade, I deleted both the node_modules and pnpm-lock.yaml before performing the new pnpm install and getting a consistent freeze.

pnpm install works fine again after I reverted back to pnpm@8.15.7.

I'm using Nx Workspace with shamefully-hoist=true as well. 

pnpm i --reporter ndjson shows frozen always after this entry:
{"time":1714171496637,"hostname":"","pid":,"level":"debug","name":"pnpm:_dependency_resolved","resolution":"@mikro-orm/core@5.9.7","wanted":{"dependentId":".","name":"@mikro-orm/core","rawSpec":"5.9.7"}}
