### ISSUE TITLE
EBUSY on Windows GitHub Action

### ISSUE THREAD

**Issue by mcollina** [pnpm/pnpm#6201]
### Last pnpm version that worked:

7.29.0

### pnpm version:

7.29.1

### Code to reproduce the issue:

Run Github Actions on a large workspace project on Windows

### Expected behavior:

Install not failing

### Actual behavior:

Take a look at https://github.com/platformatic/platformatic/actions/runs/4375185250/jobs/7656654747

---

It seems that somewhere a retry for `EBUSY` is missing.

**Comment by zkochan** [comment]
I thought graceful-fs retries on EBUSY

**Comment by mcollina** [comment]
I can consistently reproduce this on my virtualized windows environment, not just in Github Actions. If you have a fix to test I can definitely test pre-release.

**Comment by zkochan** [comment]
ok, I'll check on Windows too. Maybe I'll be able to reproduce it locally.

**Comment by zkochan** [comment]
Try 7.30.0-0

**Comment by Aliziloubaf** [comment]
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
Falling back to copying packages from store
 EBUSY  EBUSY: resource busy or locked, copyfile 'd:\pools\.pnpm-store\v3\files\91\9eded09712882972a3e568d465b89a5a1c12c81122a9f6052a47bb6d8b15127f864a0fe2246cd2ec402ae44c913751280ce297156ba41e45a75f8ddaabef4e' -> 'C:\xxx\node_modules\.pnpm\@swagger-api+apidom-core@0.69.0\node_modules\@swagger-api\_tmp_2716_bc7f600b996c76bc14cfcb02f9f226e1\cjs\index.cjs'

pnpm: EBUSY: resource busy or locked, copyfile 'd:\pools\.pnpm-store\v3\files\91\9eded09712882972a3e568d465b89a5a1c12c81122a9f6052a47bb6d8b15127f864a0fe2246cd2ec402ae44c913751280ce297156ba41e45a75f8ddaabef4e' -> 'C:\xxx\node_modules\.pnpm\@swagger-api+apidom-core@0.69.0\node_modules\@swagger-api\_tmp_2716_bc7f600b996c76bc14cfcb02f9f226e1\cjs\index.cjs'
Progress: resolved 886, reused 861, downloaded 3, added 799

C:\xxx>pnpm --version
7.30.0

The Problem exists  after installing pnpm 7.30.0

**Comment by zkochan** [comment]
Try to use a store from the `C:` drive. You can control the store location with the `store-dir` setting.

**Comment by Aliziloubaf** [comment]
Hallo zkochan,   i did set store-dir to c:\pools\.pnpm-store and the same Result

**Comment by Aliziloubaf** [comment]
![pnpm_7_30_error](https://user-images.githubusercontent.com/54585765/226277237-7a6b853d-5c56-4ce4-8c25-076736e163f1.png)

**Comment by Aliziloubaf** [comment]
can you please open the issue.  Thanks

**Comment by mcollina** [comment]
@Aliziloubaf something that is too much of a coincidence is that we both get this error as part of the `@swagger-api` package.

**Comment by Aliziloubaf** [comment]
Is there any solution for this Problem?

**Comment by Aliziloubaf** [comment]
i can not upload any Image to this issue

**Comment by Aliziloubaf** [comment]
[Ebusy_7_30_3.zip](https://github.com/pnpm/pnpm/files/11076259/Ebusy_7_30_3.zip)

**Comment by zkochan** [comment]
I cannot reproduce the issue locally on my PC. I think the only solution to try to fix it would be to add platformatic as an e2e test to pnpm.

However, I am not sure how to fix this if retry did not help.

**Comment by mcollina** [comment]
I cannot reproduce the problem anymore locally, only on actions. For some very unknown reasons some files are locked for 30+ seconds.

I think the best way to solve this it to provide a recipe on how to have your action retry automatically.

**Comment by zkochan** [comment]
Maybe we could try to read the file and then write it?

**Comment by mcollina** [comment]
I think that would be the last resort option, but it could be worth a shot.

I'm starting to think there is some bug in actions.

**Comment by zkochan** [comment]
Actually, it looks like graceful-fs added a retry only for the rename function, so it makes sense that the issue wasn't fixed: https://github.com/isaacs/node-graceful-fs/commit/ab32dabf0f0bc4ebd96434e496b5e5d630a5aa9a

**Comment by zkochan** [comment]
I have patched graceful-fs and released pnpm v7.31.0-0

Please try it @mcollina and @Aliziloubaf 

I still can't reproduce it even via CI.

**Comment by zkochan** [comment]
I have added dependencies from platformatic and they don't fail: https://github.com/pnpm/pnpm/pull/6340

**Comment by geekact** [comment]
Well, I have been encountering it for a very long time in my repository https://github.com/aomex/aomex/actions/runs/4606117155/jobs/8139017700

**Comment by zkochan** [comment]
Does v7.31.0-0 fix the issue?

**Comment by geekact** [comment]
> Does v7.31.0-0 fix the issue?

@zkochan I have tested it with v7.31.0-0 several times, and CI looks fine.

**Comment by mcollina** [comment]
This seems to be fixed for me.

**Comment by zkochan** [comment]
@mcollina do you mean with v7.31.0-0 it is fixed?

**Comment by mcollina** [comment]
I can still see this in v8.1.1: https://github.com/platformatic/platformatic/actions/runs/4616647923/jobs/8161974544?pr=848#step:5:187.

Not sure why it's so intermittent.

**Comment by Herr-Sepp** [comment]
Unfortunately, the bug also occurred with us.
Both with 7.31 and with 8.1.1

Caused by dependencies of swagger-ui
@swagger-api+apidom-parser-adapter-api-design...

I can exclude access from an anti-virus. 
It is pnpm that tries to recreate the file even though it still has an open handle on the file itself.
![pnpm_EBUSY](https://user-images.githubusercontent.com/10489458/230520123-926b8bb3-d24b-4e67-ad07-2ad30e814d79.jpg)
As you can see pnpm.exe tries to create the file twice and the second attempt is rejected. (SHARING VIOLATION)

I hope this helps to isolate the bug

**Comment by zkochan** [comment]
The fix was not released in 7.31.0 or 8.1.1

The fix is only in v7.31.0-0

**Comment by Herr-Sepp** [comment]
Yes the version v7.31.0-0 works.
Sorry I just read over the zero at the end.

**Comment by zkochan** [comment]
:ship: 7.32 and 8.2
