### ISSUE TITLE
v7.29.2 breaks the build

### ISSUE THREAD

**Issue by gfazioli** [pnpm/pnpm#6219]
### Code to reproduce the issue:

`pnpm build`

### Expected behavior:

No error in console

### Actual behavior:

```
Module not found: Can't resolve 'katex/dist/katex.min.css'
```

### Additional information:

 - `node -v` prints: 18/19 the same
 - MacOS Ventura
 - My Packages

```
"dependencies": {
    "@emotion/react": "^11.10.5",
    "@emotion/server": "^11.10.0",
    "@emotion/styled": "^11.10.5",
    "@mantine/core": "^6.0.2",
    "@mantine/dates": "^6.0.2",
    "@mantine/dropzone": "^6.0.2",
    "@mantine/hooks": "^6.0.2",
    "@mantine/next": "^6.0.2",
    "@mantine/utils": "^6.0.2",
    "@tabler/icons-react": "^2.10.0",
    "@textea/json-viewer": "^2.13.1",
    "amplitude-js": "8.8.0",
    "axios": "^0.24.0",
    "dayjs": "^1.11.7",
    "js-sha256": "0.9.0",
    "jwt-decode": "3.1.2",
    "md5": "^2.3.0",
    "next": "12.3.1",
    "nextra": "^2.2.19",
    "nextra-theme-docs": "^2.2.19",
    "nookies": "2.5.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "recharts": "2.4.3",
    "swr": "^1.3.0"
  },
  "devDependencies": {
    "@svgr/webpack": "^6.5.1",
    "@types/md5": "2.3.2",
    "@types/node": "18.7.16",
    "@types/react": "18.0.28",
    "eslint": "8.35.0",
    "eslint-config-next": "12.3.1",
    "prettier": "2.8.4",
    "typescript": "4.8.4"
  }
```
 
with my MacBook with the same env, but with pnpl v7.29.1 all worked fine, just this morning on my MacStudio after updating pnpm, stopped to work

## NPM

With `npm` everything works fine

## Downgrade

I installed `pnpm` via `brew` but I can't downgrade to `7.29.1`

**Comment by zkochan** [comment]
Maybe it [this issue](https://github.com/pnpm/pnpm/issues/6213). It is fixed in v7.29.3

**Comment by gfazioli** [comment]
> Maybe it [this issue](https://github.com/pnpm/pnpm/issues/6213). It is fixed in v7.29.3
cool, thank you
Anyway, do you know why I can't update to `7.29.3` with `brew` on Mac?
I still get the `7.93.2` as the latest... there is any timeout 🤔 
or maybe it's due to the current GutHub issues...

**Comment by zkochan** [comment]
I guess they did not update pnpm yet: https://github.com/Homebrew/homebrew-core/pull/125742

**Comment by zkochan** [comment]
Is it good now?

**Comment by yg-i** [comment]
FWIW, I'm running into the same problem trying to build this Tauri app (https://github.com/Bin-Huang/chatbox)

If I run `pnpm i` then `pnpm run dev`, I get the error message `Module not found: Can't resolve 'katex/dist/katex.min.css' in the Tauri app 

Trying with `npm` did not result in the same issue.

npm -v ⟶ 10.5.1
pnpm -v ⟶ 9.0.6

**Comment by oof2win2** [comment]
Still broken on pnpm@9.4.0

**Comment by JulyQqq** [comment]
Still broken on pnpm@9.12.3

**Comment by JulyQqq** [comment]
这是来自QQ邮箱的自动回复邮件。 
您好，您的邮件我已收到，会尽快给您回复滴~~~
