### ISSUE TITLE
v7.30.1 has somehow changed the way our dependencies work causing builds to break

### ISSUE THREAD

**Issue by ynotdraw** [pnpm/pnpm#6271]
### Code to reproduce the issue:

- Be sure you are using `pnpmv7.30.1` by running `pnpm -v` and verifying it returns `7.30.1`.
- Pull down https://github.com/CrowdStrike/ember-toucan-core
- `pnpm i`
- `cd ember-toucan-core`
- `pnpm i`
- `pnpm build`
- `cd ../test-app`
- `pnpm i`
- `ember try:each --config-path="config/ember-try.js"`
- The tests will now run using the scenario matching in the GitHub links below
- The error will occur on the "embroider" steps

The embroider steps update dependencies to use the following:

- https://github.com/embroider-build/embroider/blob/main/packages/test-setup/src/index.ts#L75

Along with the dependencies that are defined here:

- https://github.com/CrowdStrike/ember-toucan-core/blob/main/test-app/config/ember-try.js#L44-L58

Essentially we are testing against "newer" versions of packages by using these "try scenarios".

### Expected behavior:

- Expect the tests command to not fail, as it works with v7.30.0

### Actual behavior:

- Getting the error defined at https://github.com/embroider-build/embroider/issues/1378

Essentially we are hitting this line: https://github.com/embroider-build/embroider/blob/00ec2e7e58f546a5e19a23740302e49883d664d3/packages/util/addon/ember-private-api.js#L18, where it thinks we are using an older version of `ember-source` despite our `pnpm-lock.yml` saying otherwise (4.11.0).

### Additional information:

- `node -v` prints: 18.15.0
- Windows, macOS, or Linux?: GitHub Actions / CI
- Using `pnpm/action-setup@v2.2.4`, we previously specified `version: 7` as seen [here](https://github.com/CrowdStrike/ember-toucan-core/blob/76383a25cf3218bdc7fe4c2112542a379b83d6f8/.github/actions/pnpm/action.yml#L8)
- When v7.30.1 released, above picked it up and started using it
- You can see in our GitHub Actions Jobs our build began to fail https://github.com/CrowdStrike/ember-toucan-core/actions/runs/4500544412/jobs/7920001488
- I filed an issue with the package that is throwing this error at https://github.com/embroider-build/embroider/issues/1378
- It was mentioned this likely a dependency issue, so I followed all of the steps outlined in that issue
- I ultimately found that bumping the version of `pnpm` we use from `version: 7` (thus pulling in latest 7.30.1) to `version: 7.30.0` gets around the issue we are seeing [see here](https://github.com/CrowdStrike/ember-toucan-core/pull/98/files)

**Comment by zkochan** [comment]
Might be related to this issue: https://github.com/pnpm/pnpm/issues/6272

Maybe caused by this PR: https://github.com/pnpm/pnpm/pull/6220

**Comment by zkochan** [comment]
Try 7.30.2

**Comment by zkochan** [comment]
I am not sure I fixed this issue. But I also get an error with 7.30.0

```
Scenario ember-lts-4.8 + embroider-optimized: FAIL
Command run: ember test
with env: {
  "EMBROIDER_TEST_SETUP_OPTIONS": "optimized"
}
┌────────────────────┬────────────────────┬──────────────────────────────┬──────────┐
│ Dependency         │ Expected           │ Used                         │ Type     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ @embroider/core    │ ^2.1.1             │ 2.1.1                        │ pnpm     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ @embroider/webpack │ ^2.1.1             │ 2.1.1                        │ pnpm     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ @embroider/compat  │ ^2.1.1             │ 2.1.1                        │ pnpm     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ webpack            │ ^5.0.0             │ 5.75.0                       │ pnpm     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ ember-source       │ ~4.8.0             │ 4.8.4                        │ pnpm     │
└────────────────────┴────────────────────┴──────────────────────────────┴──────────┘

Scenario ember-release + embroider-optimized: SUCCESS
Command run: ember test
with env: {
  "EMBROIDER_TEST_SETUP_OPTIONS": "optimized"
}
┌────────────────────┬────────────────────┬──────────────────────────────┬──────────┐
│ Dependency         │ Expected           │ Used                         │ Type     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ @embroider/core    │ ^2.1.1             │ 2.1.1                        │ pnpm     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ @embroider/webpack │ ^2.1.1             │ 2.1.1                        │ pnpm     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ @embroider/compat  │ ^2.1.1             │ 2.1.1                        │ pnpm     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ webpack            │ ^5.0.0             │ 5.75.0                       │ pnpm     │
├────────────────────┼────────────────────┼──────────────────────────────┼──────────┤
│ ember-source       │ https://s3.amazon… │ 4.11.0-release+88df843c      │ pnpm     │
└────────────────────┴────────────────────┴──────────────────────────────┴──────────┘


1 scenarios failed
5 scenarios succeeded
6 scenarios run

```

So I am not sure I can verify it locally

**Comment by ynotdraw** [comment]
Hi @zkochan.  Thanks for jumping on this so quickly!  I attempted to use v7.30.2 and am still seeing the same error (https://github.com/CrowdStrike/ember-toucan-core/actions/runs/4511056356/jobs/7942813549?pr=101 via https://github.com/CrowdStrike/ember-toucan-core/pull/101).

**Comment by zkochan** [comment]
It seems to work with 7.30.3-0

https://github.com/zkochan/ember-headless-form/actions/runs/4511077698/jobs/7942827608
