### ISSUE TITLE
Not working with private registry

### ISSUE THREAD

**Issue by kopach** [pnpm/pnpm#708]
We are using private registry for npm modules based on artifactory. 

I have global config for npm in `~/.npmrc` like this:

```
_auth = {auth-key-here}
email = {e-mail}
always-auth = true
registry={link-to-private-registry}
```
when I run `pnpm install` I'm getting something like this:

```
  ERROR Registry returned 401 for GET on ...
```

### Code to reproduce the issue:

https://gist.github.com/kopach/3abe4da1302b28fd339ea33af7c8426d

### Additional information:

 - `node -v` prints: v6.5.0
 - Windows, OS X, or Linux?: macOS Sierra v10.12.3

**Comment by zkochan** [comment]
Same as #618 

Should be fixed probably in https://github.com/rexxars/registry-auth-token

**Comment by kopach** [comment]
Problem is still valid for me.
now it shows:

```
ERROR Registry returned 403 for GET on ...
```
`pnpm version` command: 

```
{ npm: '4.1.1',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.5.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.1.281.81',
  zlib: '1.2.8' }
```

pnpm -v
0.65.4

**Comment by zkochan** [comment]
I see, you probably have the same issue as [this](https://github.com/pnpm/pnpm/issues/718#issuecomment-296620376)

**Comment by zkochan** [comment]
Partially fixed. Lets track this issue in #718

**Comment by kopach** [comment]
Issue still valid.

The same error:
```
ERROR Registry returned 401 for GET on...
```

pnpm -v
0.65.6

**Comment by zkochan** [comment]
@kopach I looked through the logs that you attached and it seems the issue was that pnpm did not pass through the `always-auth` config value to `npm-registry-client`. I fixed it in #728.

You can try the latest pnpm.

Lets keep the issue open till we cover it with unit tests. Not so easy to cover it because we have to create a new registry mock.

**Comment by kopach** [comment]
@zkochan, thanks for fast response. Anyway, this is still not my case :)

Gist is [here](https://gist.github.com/kopach/3abe4da1302b28fd339ea33af7c8426d#file-pnpm-debug-log-v0-65-7) (I've added one more file to previous gist)

**Comment by destroyerofbuilds** [comment]
Related registry-auth-token#17

**Comment by kopach** [comment]
Issues is still reproducible :(

pnpm -v
0.66.2

**Comment by zkochan** [comment]
Sorry, I did not publish it yet. I'll post a message when it is published

**Comment by zkochan** [comment]
Landed in [v0.66.3](https://github.com/pnpm/pnpm/releases/tag/v0.66.3)

**Comment by kopach** [comment]
Now a bit different error, but problem still not solved for my case:

```ERROR This request requires auth credentials. Run `npm login` and repeat the request```

pnpm -v
0.66.4

**Comment by zkochan** [comment]
Does the error happen as well if you remove the `shrinkwrap.yaml` first?

**Comment by kopach** [comment]
I do not have `shrinkwrap.yaml` file. I do have `npm-shrinkwrap.json`, but anyway, even if I remove it - the same error appears

**Comment by zkochan** [comment]
ok, thanks will look into it again

**Comment by zkochan** [comment]
I know what is the issue with this. I'll fix it this week

**Comment by zkochan** [comment]
@kopach please try with the latest pnpm [v0.73.0](https://github.com/pnpm/pnpm/releases/tag/v0.73.0)

it should work now. pnpm now uses npm's code directly to get the auth headers

**Comment by kopach** [comment]
now I'm getting an error: 

```
ERROR This request requires auth credentials. Run `npm login` and repeat the request.
```

Updated gist with new `pnpm-debug.log` file

**Comment by zkochan** [comment]
this is weird. What does `npm c get registry` return for you?

This? `https://artifactory.finantix.com/`

**Comment by zkochan** [comment]
your registry is probably `//artifactory.finantix.com/artifactory/api/npm/`, which is correct... I know what the issue is. When getting the metadata [here](https://github.com/pnpm/pnpm/blob/master/src/network/got.ts#L64), the registry URL should be passed to `getCredentialsByURI`. I returned 0.72.0 to be latest. Probably tomorrow I'll do the fix

**Comment by zkochan** [comment]
Actually, it was easier to change than I thought, so I have a new version with the fix already.

@kopach could you please try again with `pnpm@0.73.1`. It is not published as `latest`. It is published with the `next` dist-tag.

**Comment by kopach** [comment]
unfortunately the same error 

gist updated

pnpm -v
0.73.1

**Comment by kopach** [comment]
@zkochan, registry is set to `https://artifactory.finantix.com/artifactory/api/npm/npm-release`

**Comment by zkochan** [comment]
@kopach, you can try to set it to `https://artifactory.finantix.com/artifactory/api/npm/npm-release/` and retry (a `/` is added to the end).

**Comment by kopach** [comment]
hooray 🎉 , with this workaround it works now, thanks

**Comment by zkochan** [comment]
Mystery solved! I'll make the final fix tonight.
