### ISSUE TITLE
`pnpm update --interactive` output doesn’t fit in console

### ISSUE THREAD

**Issue by ai** [pnpm/pnpm#7109]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.7.6

### Which area(s) of pnpm are affected? (leave empty if unsure)

CLI

### Reproduction steps

```sh
pnpm update --interactive
```

I have bug at least in `zsh` on `Black Box` terminal.

### Describe the Bug

I very like how many information we have on new CLI UI for `pnpm update --interactive`, but:

1. The dependencies selection the output looks bad on standard 80 columns window. Even if we have space to fit everything.
2. After selecting the dependencies the output looks weird on any window size

Issue 1 and 2 on normal window:
![Captura desde 2023-09-18 23-04-34](https://github.com/pnpm/pnpm/assets/19343/516a5012-6876-460b-b7bf-447af03bfaf1)
![Captura desde 2023-09-18 23-04-58](https://github.com/pnpm/pnpm/assets/19343/17b90753-d07a-4c8c-9b24-86c66c42de5c)

Issue 2 on big window:
![Captura desde 2023-09-18 23-05-34](https://github.com/pnpm/pnpm/assets/19343/3f72651c-2fd4-4631-a001-2831942c61bb)

### Expected Behavior

1. When we render table we can get current window screen and try to choose table columns to fit everything
2. The second issue looks like a bug

Maybe it is an issue in new library used to render that selection UI? We have no problem on previous UI. I can open issue there.

### Which Node.js version are you using?

20.6.1

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux

### If your OS is a Linux based, which one it is? (Include the version if relevant)

Fedora 38

**Comment by IronGeek** [comment]
I'm not sure if this is related,
but when the interactive update list contains a package with an _unsually-long-string_ as version, the package name on the next line become obscured...

![image](https://github.com/pnpm/pnpm/assets/1383932/01d768ab-7dde-4733-b153-64b592bbb80a)

Notice the package below `bun-types` is `<empty>` (it should be `rollup`)

**Comment by ai** [comment]
Fixed in latest version

**Comment by MoKhajavi75** [comment]
Hey

Sorry to mention @ai but this issue still exists in the latest version (pnpm v9.12.1)

![image](https://github.com/user-attachments/assets/5148364e-4973-40da-8c4d-02e3dc6da355)

Since the version of `@swc/cli` is too long, the last line disappeared!
