### ISSUE TITLE
Error Changing Node Versions

### ISSUE THREAD

**Issue by tris203** [pnpm/pnpm#7161]
### Verify latest release

- [X] I verified that the issue exists in the latest pnpm release

### pnpm version

8.8.0

### Reproduction steps

```
PS C:\Users\tris2\VSCode> pnpm -v         
8.8.0
PS C:\Users\tris2\VSCode> node -v
v20.8.0
PS C:\Users\tris2\VSCode> pnpm env use -g lts   
 EPERM  EPERM: operation not permitted, unlink 'C:\Users\tris2\AppData\Local\pnpm\node.exe'

pnpm: EPERM: operation not permitted, unlink 'C:\Users\tris2\AppData\Local\pnpm\node.exe'
    at Object.unlink (node:internal/fs/sync:93:18)
    at Object.unlinkSync (node:fs:1853:17)
    at envUse (C:\ProgramData\npm\node_modules\pnpm\dist\pnpm.cjs:108526:31)
    at async C:\ProgramData\npm\node_modules\pnpm\dist\pnpm.cjs:217464:21
    at async main (C:\ProgramData\npm\node_modules\pnpm\dist\pnpm.cjs:217431:34)
    at async runPnpm (C:\ProgramData\npm\node_modules\pnpm\dist\pnpm.cjs:217688:5)
    at async C:\ProgramData\npm\node_modules\pnpm\dist\pnpm.cjs:217680:7
```

### Describe the Bug

When trying to switch node versions through env use, i get the error.

I have tried:

```
PS C:\Users\tris2\VSCode> pnpm.cmd add -g pnpm @pnpm/exe
Nothing to stop. No server is running for the store at C:\Users\tris2\AppData\Local\pnpm\store\v3
Already up to date
Progress: resolved 7, reused 3, downloaded 0, added 0, done
Done in 1.4s
```

as suggested in #5700 

I opened a new issue as that seemed to be reported in v7 and this is a new major version

### Expected Behavior

Node to switch version

### Which Node.js version are you using?

20.8.0

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by tris203** [comment]
Potentially resolved by closing IDE

Opening a new powershell and running

```
iwr https://get.pnpm.io/install.ps1 -useb | iex
```
again.

It reported no changes, but switching versions seems to work now

```
PS C:\> pnpm env use --global 14 
Node.js 14.21.3 is activated
C:\Users\tris2\AppData\Local\pnpm\node.exe -> C:\Users\tris2\AppData\Local\pnpm\nodejs\14.21.3\node.exe
PS C:\> node -v
v14.21.3
PS C:\> pnpm env use --global lts   
Node.js 18.18.0 is activated
C:\Users\tris2\AppData\Local\pnpm\node.exe -> C:\Users\tris2\AppData\Local\pnpm\nodejs\18.18.0\node.exe
PS C:\> pnpm env use --global latest
Node.js 20.8.0 is activated
C:\Users\tris2\AppData\Local\pnpm\node.exe -> C:\Users\tris2\AppData\Local\pnpm\nodejs\20.8.0\node.exe
```

**Comment by josh-hemphill** [comment]
I still get the error, even after using powershell, even if I run in admin shell. I think I've tried very possible combination.

**Comment by josh-hemphill** [comment]
Well I think I did fix it by manually deleting my pnpm folders.

**Comment by Lorondos** [comment]
Deleting just the node.exe it complains about, not allowing an overwrite for some reason.
