### ISSUE TITLE
Since #7278 an empty workspace throws `ERR_PNPM_INVALID_WORKSPACE_CONFIGURATION  Expected object but found - null`

### ISSUE THREAD

**Issue by Jolg42** [pnpm/pnpm#7307]
### Last pnpm version that worked

8.10.3

### pnpm version

8.10.4

### Code to reproduce the issue

https://github.com/prisma/prisma/blob/5acf00664799d98ab193b33f48620696ffc41fa5/packages/client/tests/e2e/nextjs-schema-not-found/3_simplerepo-noServerComponents-noCustomOutput-noReExport/pnpm-workspace.yaml

The `pnpm-workspace.yaml` is empty.
Run `pnpm install`

### Expected behavior

It used to work before, and was used to put a boundary to the workspace inside our monorepo in some tests.

### Actual behavior

https://github.com/prisma/prisma/actions/runs/6852265875/job/18630433790?pr=21922#step:5:293
```
 🛑 nextjs-schema-not-found/3_simplerepo-noServerComponents-noCustomOutput-noReExport failed with exit code 1
$ cat /home/runner/work/prisma/prisma/packages/client/tests/e2e/nextjs-schema-not-found/3_simplerepo-noServerComponents-noCustomOutput-noReExport/LOGS.txt
$ pnpm install
 ERR_PNPM_INVALID_WORKSPACE_CONFIGURATION  Expected object but found - null
/usr/local/lib/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
```

### Additional information

We added that to signal a boundary to our monorepo. It's a subdirectory used for some end-to-end tests and there are no packages.

I found a similar report in a different issue:

              With https://github.com/pnpm/pnpm/pull/7278 an empty workspace configuration in `bar/` does not work anymore. It throws this error:

```
ERR_PNPM_INVALID_WORKSPACE_CONFIGURATION  Expected object but found - null
```

Looks like you can add
```yaml
packages:
  - "**"
```
to `bar/pnpm-workspace.yaml` to fix this.

_Originally posted by @florianmutter in https://github.com/pnpm/pnpm/issues/2412#issuecomment-1807573622_
            

### Node.js version

16.20.2

### Operating System

Linux

**Comment by Jolg42** [comment]
I tried the workaround from @florianmutterof of defining
```
packages:
  - "**"
```
https://github.com/prisma/prisma/pull/21925

And it worked in our setup. (https://github.com/prisma/prisma/actions/runs/6853033906/job/18632953151?pr=21925)

**Comment by Jolg42** [comment]
Maybe it's not an intended usage but I figured, let's create a proper issue to discuss this. And for others to find it via search.

**Comment by zkochan** [comment]
I think this should be fixed. It is a breaking change.

**Comment by Jolg42** [comment]
Thanks 🙌🏼 💚

**Comment by stybo** [comment]
https://stackblitz.com/~/github.com/Stybo/test-table?file=pnpm-workspace.yaml

I have the same problem that is not fixed after adding:
```packages:
  - "**"
```
Can someone have a look? Works all locally
