### ISSUE TITLE
Using `~` as a save-prefix

### ISSUE THREAD

**Issue by nikoladev** [pnpm/pnpm#888]
With `npm` and `yarn` you can use `~` as a save-prefix so that when you install a package it gets added with the `~` semver modifier to your package.json. Example:

```bash
> npm config set save-prefix='~'
> npm i express
> cat package.json
... # package.json stuff
  "dependencies": {
    "express": "~4.15.4"
  }
... # package.json stuff
```

With `pnpm` it looks like this it still uses `^`:

```bash
> pnpm config set save-prefix='~'
> pnpm i express
> cat package.json
... # package.json stuff
  "dependencies": {
    "express": "^4.15.4"
############## ^^^^^^^^^ the important part
  }
... # package.json stuff
```

It's not a deal breaker, but I do have to edit the package.json manually after installing packages and then run `pnpm i` again to make sure everything is set correctly (like the `specifiers` at the bottom of `.shrinkwrap.yaml`).

**Comment by zkochan** [comment]
This is fixed in `pnpm@1.14.4`

**Comment by randomer** [comment]
@zkochan First of all, thanks for creating and maintaining pnpm, it saved me a lot of time and space! But it looks like it’s still a problem in `5.1.8`. Should I create a new issue or can you reopen this one?

**Comment by zkochan** [comment]
create a new one with steps. It cannot be the same issue. There are tests that cover it.
