### ISSUE TITLE
Can't use `pnpm approve-builds` locally

### ISSUE THREAD

**Issue by SukkaW** [pnpm/pnpm#9045]
### Verify latest release

- [x] I verified that the issue exists in the latest pnpm release

### Which area(s) of pnpm are affected? (leave empty if unsure)

Package manager compatibility

### Reproduction steps

- Install `better-sqlite3` with `pnpm@9`
- Upgrade pnpm from 9 to 10.2.0
- Run `pnpm approve-builds`

### Describe the Bug

Locally pnpm prints when running `pnpm approve-builds`:

```
There are no packages awaiting approval
```

However on CI I see:

```
Ignored build scripts: @swc/core, better-sqlite3. Run "pnpm approve-builds" to pick which dependencies should be allowed to run scripts.
```

This causes CI fails to build while it works locally.

### Expected Behavior

The local environment and the CI environment behavior should be consistent.

### Which Node.js version are you using?

22.13.1

### Which operating systems have you used?

- [x] macOS
- [ ] Windows
- [x] Linux

**Comment by zkochan** [comment]
Run `pnpm install` first, then try `pnpm approve-builds` again.

Also, you can manually add this to your package.json:

```json
{
  "pnpm": {
    "onlyBuiltDependencies": ["@swc/core", "better-sqlite3"]
  }
}
```

**Comment by hyoretsu** [comment]
![Image](https://github.com/user-attachments/assets/ff1ae1c8-8584-4a30-b03a-3786f3e4bcb3)

**Comment by SukkaW** [comment]
> Run `pnpm install` first, then try `pnpm approve-builds` again.

I already tried that, and it was still `There are no packages awaiting approval`.

> Also, you can manually add this to your package.json:
> 
> {
>   "pnpm": {
>     "onlyBuiltDependencies": ["@swc/core", "better-sqlite3"]
>   }
> }

That's what I did. But I want to use `pnpm approve-builds` for migration. If this issue happens consistently, I need to add `onlyBuiltDependencies` to every `package.json` manually.

**Comment by zkochan** [comment]
Try with pnpm 10.2.1, I have published a fix.

**Comment by SukkaW** [comment]
> Try with pnpm 10.2.1, I have published a fix.

It's still the same.

But if I delete `node_modules` and then run `pnpm i` will I get `Ignored build scripts:` (and `pnpm approve-builds` will show options). 

If I don't delete `node_modules` and then `pnpm i` after updating pnpm, I won't get this warning, and `pnpm approve-builds` returns `There are no packages awaiting approval`.

**Comment by denkoleda** [comment]
@SukkaW thanks for sharing. Had the same problem, sad this ignored build scripts message in build env and not in local until I removed `node_modules`

**Comment by Mochitto** [comment]
Writing here so that I can know when they fix this lol

Broke my CI as well :/

**Comment by SukkaW** [comment]
> But if I delete `node_modules` and then run `pnpm i` will I get `Ignored build scripts:` (and `pnpm approve-builds` will show options).
> 
> If I don't delete `node_modules` and then `pnpm i` after updating pnpm, I won't get this warning, and `pnpm approve-builds` returns `There are no packages awaiting approval`.

Also after deleting `node_modules` and then run `pnpm i`, `Ignored build scripts` warning will pop up.

But if you run `pnpm i` again (a.k.a. twice in a row), now it becomes `There are no packages awaiting approval`.

Once again, this demonstrates how badly pnpm put this breaking change together and how this feature is implemented in a way broken by default.
